set(CMAKE_SYSTEM_NAME WindowsStore)
set(CMAKE_SYSTEM_VERSION 10.0)

set(CMAKE_SYSTEM_PROCESSOR AMD64)

set(CMAKE_STAGING_PREFIX ${CMAKE_CURRENT_LIST_DIR}/build)
set(tools /usr/bin)

set(CMAKE_C_COMPILER ${tools}/x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER ${tools}/x86_64-w64-mingw32-g++)


SET(CMAKE_CXX_FLAGS -Wall)
SET(CMAKE_EXE_LINKER_FLAGS -static)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
